name: (TEST) Tag branch

on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'autotag'
      - uses: vakus/dotnet-deployment-versioning@main
      
